GRANT CONNECT ON DATABASE :"database_name" TO :"user_name";

/* public schema read/write acces */
GRANT USAGE ON SCHEMA public TO :"user_name";
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO :"user_name";
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO :"user_name";
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO :"user_name";
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO :"user_name";

/* poa schema read/write acces */
GRANT USAGE ON SCHEMA poa TO :"user_name";
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA poa TO :"user_name";
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA poa TO :"user_name";
ALTER DEFAULT PRIVILEGES IN SCHEMA poa GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO :"user_name";
ALTER DEFAULT PRIVILEGES IN SCHEMA poa GRANT USAGE, SELECT ON SEQUENCES TO :"user_name";

/* supervision schema read/write acces */
GRANT USAGE ON SCHEMA supervision TO :"user_name";
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA supervision TO :"user_name";
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA supervision TO :"user_name";
ALTER DEFAULT PRIVILEGES IN SCHEMA supervision GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO :"user_name";
ALTER DEFAULT PRIVILEGES IN SCHEMA supervision GRANT USAGE, SELECT ON SEQUENCES TO :"user_name";

/* supervision_finance schema read/write acces */
GRANT USAGE ON SCHEMA supervision_finance TO :"user_name";
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA supervision_finance TO :"user_name";
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA supervision_finance TO :"user_name";
ALTER DEFAULT PRIVILEGES IN SCHEMA supervision_finance GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO :"user_name";
ALTER DEFAULT PRIVILEGES IN SCHEMA supervision_finance GRANT USAGE, SELECT ON SEQUENCES TO :"user_name";

/* analytics_export schema read/insert acces */
GRANT USAGE ON SCHEMA analytics_export TO :"user_name";
GRANT SELECT, INSERT ON ALL TABLES IN SCHEMA analytics_export TO :"user_name";
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA analytics_export TO :"user_name";
ALTER DEFAULT PRIVILEGES IN SCHEMA analytics_export GRANT SELECT, INSERT ON TABLES TO :"user_name";
ALTER DEFAULT PRIVILEGES IN SCHEMA analytics_export GRANT USAGE, SELECT ON SEQUENCES TO :"user_name";
