---
services:
  data-sync:
    image: data-sync:latest
    build:
      context: .
      platforms:
        - "linux/arm64/v8"
        - "linux/amd64"

  postgresql:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: opgadmin
      POSTGRES_PASSWORD: NotARealPassword123
    healthcheck:
      test: pg_isready --username=opgadmin --dbname=NotARealPassword123
      interval: 10s
      timeout: 5s
      retries: 5

  create-database:
    image: data-sync:latest
    environment:
      PGHOST: postgresql
      PGPORT: 5432
      PGPASSWORD: NotARealPassword123
      PGUSER: opgadmin
    volumes:
      - ./test/setup_sirius_db.sql:/tmp/setup_sirius_db.sql
    command: psql --file=/tmp/setup_sirius_db.sql

  create-roles:
    image: data-sync:latest
    environment:
      PGHOST: postgresql
      PGPORT: 5432
      PGPASSWORD: NotARealPassword123
      PGUSER: opgadmin
      DATABASE_NAME: api
      SEARCH_APP_USER_PASSWORD: NotARealSearchPassword123
      SIRIUS_APP_USER_PASSWORD: NotARealSiriusPassword123
      SUPERVISION_FINANCE_APP_USER_PASSWORD: NotARealFinancePassword123
      OPERATOR_PASSWORD: NotARealOperatorPassword123
    command: /app/create-roles.sh

  database-tuning:
    image: data-sync:latest
    environment:
      PGHOST: postgresql
      PGPORT: 5432
      PGPASSWORD: NotARealPassword123
      PGUSER: opgadmin
      DATABASE_NAME: api
    command: /app/database-tuning.sh
