---
services:
  data-sync:
    image: 311462405659.dkr.ecr.eu-west-1.amazonaws.com/sirius/data-sync:latest
    build:
      context: .

  postgresql:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: opgadmin
      POSTGRES_PASSWORD: NotARealPassword123
    healthcheck:
      test: pg_isready --username=opgadmin --dbname=NotARealPassword123
      interval: 10s
      timeout: 5s
      retries: 5

  create-database:
    image: 311462405659.dkr.ecr.eu-west-1.amazonaws.com/sirius/data-sync:latest
    environment:
      PGHOST: postgresql
      PGPORT: 5432
      PGPASSWORD: NotARealPassword123
      PGUSER: opgadmin
    volumes:
      - ./test/setup_sirius_db.sql:/tmp/setup_sirius_db.sql
    command: psql --file=/tmp/setup_sirius_db.sql

  create-roles:
    image: 311462405659.dkr.ecr.eu-west-1.amazonaws.com/sirius/data-sync:latest
    environment:
      PGHOST: postgresql
      PGPORT: 5432
      PGPASSWORD: NotARealPassword123
      PGUSER: opgadmin
      DATABASE_NAME: api
      SEARCH_APP_USER_PASSWORD: NotARealSearchPassword123
      SIRIUS_APP_USER_PASSWORD: NotARealSiriusPassword123
      SUPERVISION_FINANCE_APP_USER_PASSWORD: NotARealFinancePassword123
      OPERATOR_PASSWORD: NotARealOperatorPassword123
    command: /app/create-roles.sh

  database-tuning:
    image: 311462405659.dkr.ecr.eu-west-1.amazonaws.com/sirius/data-sync:latest
    environment:
      PGHOST: postgresql
      PGPORT: 5432
      PGPASSWORD: NotARealPassword123
      PGUSER: opgadmin
      DATABASE_NAME: api
    command: /app/database-tuning.sh
